### ISSUE TITLE
Beatmap status not updated / Leaderboard ranking mess

### ISSUE THREAD

**Issue by jebwizoscar** [peppy/osu-api#95]
1. beatmaps like 393291 shows 'Qualified' in API but it's actually ranked
https://osu.ppy.sh/api/get_beatmaps?k=(key)&b=393291

2. more than 20 beatmaps like 472612
shows different orders in API and website (and I think the latter is right)
https://osu.ppy.sh/api/get_scores?k=(key)&b=472612
https://osu.ppy.sh/b/472612

**Comment by Repflez** [comment]
For 2:
On API, the first score has a larger `enabled_mods` value (1656 -> HD,HR,NC,FL,SD) and the other 2 have 1112 (HD,HR,NC,FL) as their value. Maybe is taking in account the enabled mods to order in case of same scores instead of time like the site.

**Comment by jebwizoscar** [comment]
@Repflez :
but OvO has the same mod as Haxwell in this example, and OvO's score is later than Haxwell's

**Comment by Repflez** [comment]
@jebwizoscar: I don't understand. All 3 users have the same score.
```
array (size=50)
  0 => 
    array (size=15)
      'score' => string '1582720' (length=7)
      'username' => string 'Kashiwazaki Sena' (length=16)
      'maxcombo' => string '330' (length=3)
      'count50' => string '0' (length=1)
      'count100' => string '0' (length=1)
      'count300' => string '180' (length=3)
      'countmiss' => string '0' (length=1)
      'countkatu' => string '0' (length=1)
      'countgeki' => string '41' (length=2)
      'perfect' => string '1' (length=1)
      'enabled_mods' => string '1656' (length=4)
      'user_id' => string '1502556' (length=7)
      'date' => string '2014-11-24 15:58:19' (length=19)
      'rank' => string 'XH' (length=2)
      'pp' => string '65.9349' (length=7)
  1 => 
    array (size=15)
      'score' => string '1582720' (length=7)
      'username' => string 'OvO' (length=3)
      'maxcombo' => string '330' (length=3)
      'count50' => string '0' (length=1)
      'count100' => string '0' (length=1)
      'count300' => string '180' (length=3)
      'countmiss' => string '0' (length=1)
      'countkatu' => string '0' (length=1)
      'countgeki' => string '41' (length=2)
      'perfect' => string '1' (length=1)
      'enabled_mods' => string '1112' (length=4)
      'user_id' => string '1517064' (length=7)
      'date' => string '2015-01-14 19:27:17' (length=19)
      'rank' => string 'XH' (length=2)
      'pp' => string '65.9349' (length=7)
  2 => 
    array (size=15)
      'score' => string '1582720' (length=7)
      'username' => string 'Haxwell' (length=7)
      'maxcombo' => string '330' (length=3)
      'count50' => string '0' (length=1)
      'count100' => string '0' (length=1)
      'count300' => string '180' (length=3)
      'countmiss' => string '0' (length=1)
      'countkatu' => string '0' (length=1)
      'countgeki' => string '41' (length=2)
      'perfect' => string '1' (length=1)
      'enabled_mods' => string '1112' (length=4)
      'user_id' => string '1726105' (length=7)
      'date' => string '2014-11-23 22:42:18' (length=19)
      'rank' => string 'XH' (length=2)
      'pp' => string '65.9349' (length=7)
...
```
The only difference I'm seeing here besides time are the mods enabled and that the scores are being ordered by `enabled_mods`.

**Comment by jebwizoscar** [comment]
@Repflez I say 'date' :p 
scores are ordered by score and then by date I think but I don't know what's the behavior of the API.

**Comment by peppy** [comment]
1. Fixed.

2. Both now use the same code path, so this should be fixed already. Please check again.

**Comment by TheHowl** [comment]
The issue is still there. In the OP's sample API call the top scores are ordered this way:

1. OvO
2. nyunpo
3. [ToshKa]
4. PrivateSquare...

While on the beatmap ranking page, it's in this order:

1. Haxwell
2. [ToshKa]
3. Hinabita
4. Suwako...

**Comment by peppy** [comment]
Okay, found the reason this is still happening. Should be resolved now.

**Comment by TheHowl** [comment]
Yup. Checked OP's example, it seems fixed now.
